title: HAMK BYOD
description: Following these guidelines, you will be able to set up your personal device for educational purposes.
show_downloads: false
theme: jekyll-theme-dinky
github:
  is_project_page: false